import fs from 'node:fs';
import path from 'node:path';
import crypto from 'node:crypto';
import { docker } from './dockerctl.js';
import { hostPath, LETSENCRYPT_DIR, WEBROOT_DIR } from './paths.js';

const IMAGE = 'certbot/certbot:latest';

// certbot runs as a throwaway container rather than a stack service: it needs
// to run rarely, and the volumes it wants are the same host directories nginx
// already serves the ACME webroot from. Paths must be the *host* paths because
// it is the Docker daemon, not this container, that resolves them.
/**
 * The DuckDNS hook, written where both issuing and renewing can reach it.
 *
 * DNS-01 is the only way to get a certificate when ports 80 and 443 belong to
 * something else on the network: Let's Encrypt asks for a TXT record instead of
 * an inbound HTTP request, and DuckDNS sets one through the same token the
 * panel already holds.
 *
 * The path matters more than it looks. certbot writes the hook command into the
 * renewal config and runs it again every ninety days, so a hook living anywhere
 * temporary works today and stops working silently in three months. This lives
 * in the letsencrypt volume, which renewals mount too.
 *
 * Python because the certbot image is built on it. curl is not guaranteed.
 */
const HOOK_PATH = '/etc/letsencrypt/duckdns-hook.py';

const HOOK = `#!/usr/bin/env python3
# Generated by the Quick Start Home panel.
#
# Sets the ACME TXT record on a DuckDNS name, and clears it afterwards. DuckDNS
# serves whatever is passed here at _acme-challenge.<name>.duckdns.org, which is
# where Let's Encrypt looks.
import os, sys, time, urllib.parse, urllib.request

# The name comes from certbot, not from the environment: renewal runs over
# every certificate in turn, and a subdomain injected once would put the TXT
# record on whichever name happened to be first.
domain = os.environ.get("CERTBOT_DOMAIN", "")
if not domain.endswith(".duckdns.org"):
    sys.exit("This hook only handles DuckDNS names, and CERTBOT_DOMAIN was: " + (domain or "empty"))
sub = domain[: -len(".duckdns.org")]
token = os.environ["DUCKDNS_TOKEN"]
cleanup = len(sys.argv) > 1 and sys.argv[1] == "cleanup"
value = "" if cleanup else os.environ.get("CERTBOT_VALIDATION", "")

query = {"domains": sub, "token": token, "txt": value or "removed"}
if cleanup:
    query["clear"] = "true"

with urllib.request.urlopen("https://www.duckdns.org/update?" + urllib.parse.urlencode(query), timeout=30) as res:
    body = res.read().decode().strip()
if body != "OK":
    sys.exit("DuckDNS refused the TXT update: " + body)

# Let's Encrypt asks the authoritative servers directly, and can ask sooner than
# the record has settled. A failed validation costs an hour of rate limit, so
# this waits rather than races.
if not cleanup:
    time.sleep(30)
`;

function writeHook() {
    fs.mkdirSync(LETSENCRYPT_DIR, { recursive: true });
    fs.writeFileSync(path.join(LETSENCRYPT_DIR, 'duckdns-hook.py'), HOOK, { mode: 0o755 });
}

function volumeArgs() {
    return [
        '-v',
        `${hostPath('proxy', 'letsencrypt')}:/etc/letsencrypt`,
        '-v',
        `${hostPath('proxy', 'webroot')}:/var/www/certbot`,
    ];
}

/**
 * An ACME account can be registered without a contact address, and this one is.
 *
 * The address only ever receives expiry warnings, and this stack renews on a
 * daily timer and shows the expiry date in the panel, so the warning would be
 * telling someone something their own screen already says. Asking for it made
 * every setup one field longer for that.
 */
export async function issue(domain, email, { staging = false, onLine, duckdns = null } = {}) {
    const contact = String(email || '').trim();
    if (duckdns) writeHook();

    const args = [
        'run',
        '--rm',
        ...volumeArgs(),
        // The token goes in the environment rather than on the command line, so
        // it never appears in a process listing on this machine.
        ...(duckdns ? ['-e', `DUCKDNS_SUBDOMAIN=${duckdns.subdomain}`, '-e', `DUCKDNS_TOKEN=${duckdns.token}`] : []),
        IMAGE,
        'certonly',
        ...(duckdns
            ? [
                  '--manual',
                  '--preferred-challenges',
                  'dns',
                  '--manual-auth-hook',
                  HOOK_PATH,
                  '--manual-cleanup-hook',
                  `${HOOK_PATH} cleanup`,
              ]
            : ['--webroot', '-w', '/var/www/certbot']),
        '--non-interactive',
        // Inside the letsencrypt volume, so the log outlives this throwaway
        // container. certbot's own error message points at it, and until now it
        // named a path that ceased to exist the moment it was printed.
        '--logs-dir',
        '/etc/letsencrypt/logs',
        '--agree-tos',
        '--no-eff-email',
        '--keep-until-expiring',
        ...(contact ? ['-m', contact] : ['--register-unsafely-without-email']),
        '-d',
        domain,
    ];
    if (staging) args.push('--staging');
    return docker(args, { onLine, timeoutMs: 5 * 60_000 });
}

/**
 * Serves a file the way Let's Encrypt is about to ask for one, and fetches it
 * back through nginx.
 *
 * A failed challenge has two very different causes -- this machine not serving
 * it, or the internet not reaching this machine -- and certbot cannot tell them
 * apart. This can: if the file comes back over the internal network, everything
 * on this side is right and what is missing is the route in.
 */
export async function selfTest(domain) {
    const token = `panel-check-${crypto.randomBytes(8).toString('hex')}`;
    const dir = path.join(WEBROOT_DIR, '.well-known', 'acme-challenge');
    const file = path.join(dir, token);
    const expected = `served-by-${domain}`;

    try {
        fs.mkdirSync(dir, { recursive: true });
        fs.writeFileSync(file, expected, 'utf8');
        const res = await fetch(`http://proxy/.well-known/acme-challenge/${token}`, {
            headers: { Host: domain },
            signal: AbortSignal.timeout(5000),
        });
        return { ok: res.ok && (await res.text()).trim() === expected };
    } catch (err) {
        return { ok: false, error: err.message };
    } finally {
        try {
            fs.rmSync(file);
        } catch {
            /* nothing to clean up */
        }
    }
}

/**
 * Renewal re-runs whatever challenge each certificate was issued with, so a
 * DuckDNS one needs the hook and the token here again. They are passed whenever
 * the stack has them: a certificate issued over HTTP simply never asks.
 */
export async function renew({ onLine, duckdns = null } = {}) {
    if (duckdns) writeHook();
    return docker(
        [
            'run',
            '--rm',
            ...volumeArgs(),
            ...(duckdns ? ['-e', `DUCKDNS_SUBDOMAIN=${duckdns.subdomain}`, '-e', `DUCKDNS_TOKEN=${duckdns.token}`] : []),
            IMAGE,
            'renew',
            // No --webroot here on purpose. Flags passed to `renew` override
            // what each certificate was issued with, so naming an authenticator
            // would force every certificate through it -- and a DuckDNS one
            // renewed over webroot asks for a port that is not open, three
            // months from now, with nobody watching. Each renewal config
            // already records its own, webroot ones included.
            '--non-interactive',
        ],
        { onLine, timeoutMs: 10 * 60_000 },
    );
}

export async function revokeAndDelete(domain, { onLine } = {}) {
    return docker(
        ['run', '--rm', ...volumeArgs(), IMAGE, 'delete', '--cert-name', domain, '--non-interactive'],
        { onLine, timeoutMs: 2 * 60_000 },
    );
}
