#!/usr/bin/env bash
#
# Develop against a running stack.
#
# The installer copies this repo into ~/.quickstart-home and `docker build` bakes the
# manager's files into an image, so editing the repo normally changes nothing
# that is running -- there are three copies and the browser sees the third.
#
#   ./dev.sh link     mount this repo's manager into the running container,
#                     so editing a file here changes what the browser gets
#   ./dev.sh watch    link, then restart the panel on every change and let the
#                     open browser tab reload itself
#   ./dev.sh unlink   go back to the files baked into the image
#   ./dev.sh sync     copy this repo into the install dir and rebuild for real
#   ./dev.sh status    show which copy is live
#
# After `link`:
#   - public/ (HTML, CSS, JS) is re-read per request, so a browser refresh is enough
#   - server.js and lib/ need `./dev.sh restart` -- Node does not reload itself
#
# `watch` removes both of those chores. Nothing outside manager/ is mounted,
# though: docker-compose.yml, nextcloud/ and the installers are read from the
# install directory, so changing those still means ./dev.sh sync.

set -euo pipefail

REPO="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
STACK_DIR="${QSH_STACK_DIR:-$HOME/.quickstart-home}"
OVERRIDE="$STACK_DIR/conf/dev.yml"

if [ -t 1 ]; then
    B=$'\033[1m'; DIM=$'\033[2m'; GRN=$'\033[32m'; YLW=$'\033[33m'; RED=$'\033[31m'; CYN=$'\033[36m'; R=$'\033[0m'
else
    B=""; DIM=""; GRN=""; YLW=""; RED=""; CYN=""; R=""
fi
say()  { printf '%s==>%s %s\n' "$CYN" "$R" "$*"; }
ok()   { printf '%s  ok%s %s\n' "$GRN" "$R" "$*"; }
die()  { printf '%sfail%s %s\n' "$RED" "$R" "$*" >&2; exit 1; }

[ -d "$STACK_DIR" ] || die "No install found at $STACK_DIR. Run install.sh first."

DOCKER_SUDO=""
docker info >/dev/null 2>&1 || DOCKER_SUDO="sudo"

dc() {
    local files=(-f "$STACK_DIR/docker-compose.yml")
    for extra in conf/apps-ports.yml conf/dev.yml; do
        [ -f "$STACK_DIR/$extra" ] && files+=(-f "$STACK_DIR/$extra")
    done
    $DOCKER_SUDO docker compose "${files[@]}" --project-directory "$STACK_DIR" "$@"
}

# Mounts the working copy over the files baked into the image. Both `link` and
# `watch` need it, and running it twice is harmless.
# Files the running stack reads from the install directory, not from the mount.
# The manager's own code can be mounted over the image; a compose file cannot,
# because it is the docker CLI inside the container that reads it, from /stack.
STACK_ITEMS="docker-compose.yml manager nextcloud uninstall.sh README.md"

copy_stack_items() {
    for item in $STACK_ITEMS; do
        [ -e "$REPO/$item" ] || continue
        rm -rf "${STACK_DIR:?}/${item:?}"
        cp -R "$REPO/$item" "$STACK_DIR/$item"
    done
    cp "$REPO/proxy/nginx-base.conf" "$STACK_DIR/proxy/nginx-base.conf" 2>/dev/null || true
}

link_repo() {
    # Mounting the manager is not enough on its own. A service added to the
    # compose file is invisible until that file reaches the install directory,
    # and the failure reads as "no such service", which sounds like a bug in the
    # panel rather than a stale copy of a file.
    copy_stack_items
    mkdir -p "$STACK_DIR/conf"
    # Read-only: the container should never write back into the repo.
    cat > "$OVERRIDE" <<YAML
# Generated by dev.sh -- development only.
# Mounts the working copy over the files baked into the manager image so edits
# in the repo take effect without a rebuild. Remove with ./dev.sh unlink.
services:
  manager:
    volumes:
      - $REPO/manager/public:/app/public:ro
      - $REPO/manager/lib:/app/lib:ro
      - $REPO/manager/server.js:/app/server.js:ro
YAML
    say "Linking $REPO/manager into the running container"
    dc up -d --force-recreate manager >/dev/null
    ok "Linked. Edit files in $REPO/manager and refresh the browser."
    printf '%s  server.js and lib/ still need ./dev.sh restart, or use ./dev.sh watch%s\n' "$DIM" "$R"
}

case "${1:-status}" in
    link)
        link_repo
        ;;

    watch)
        link_repo
        say "Watching $REPO/manager. Every change restarts the panel."
        printf '%s  the open tab notices the restart and reloads itself%s\n' "$DIM" "$R"
        printf '%s  ctrl-c to stop; the repo stays linked until ./dev.sh unlink%s\n\n' "$DIM" "$R"

        stamp="$(mktemp)"
        trap 'rm -f "$stamp"; printf "\n"; say "Stopped watching. Still linked -- ./dev.sh unlink restores the image."; exit 0' INT TERM

        while :; do
            sleep 1
            # -print -quit stops at the first hit. This only needs to know that
            # something changed, not to enumerate everything that did.
            changed="$(find "$REPO/manager" -type f -newer "$stamp" -print -quit 2>/dev/null || true)"
            [ -n "$changed" ] || continue

            say "changed ${changed#"$REPO"/}"
            if dc restart manager >/dev/null 2>&1; then
                ok "panel restarted"
            else
                printf '%s  restart failed. Run ./dev.sh status to see what is live.%s\n' "$YLW" "$R"
            fi
            # An editor writes several files in a burst, and a restart takes a
            # moment of its own. Settle first, then take the timestamp, so one
            # save cannot queue three restarts.
            sleep 1
            touch "$stamp"
        done
        ;;

    unlink)
        rm -f "$OVERRIDE"
        say "Restoring the files baked into the image"
        dc up -d --force-recreate manager >/dev/null
        ok "Unlinked."
        ;;

    restart)
        say "Restarting the manager"
        dc restart manager >/dev/null
        ok "Restarted."
        ;;

    sync)
        # The permanent path: what a user re-running the installer would get.
        say "Copying the repo into $STACK_DIR and rebuilding"
        copy_stack_items
        rm -f "$OVERRIDE"
        dc build manager
        dc up -d --force-recreate manager >/dev/null
        ok "Rebuilt from the current repo."
        ;;

    status)
        printf '\n%sWhich copy is live%s\n' "$B" "$R"
        printf '  repo        %s\n' "$REPO/manager/public/app.js"
        printf '  install dir %s\n' "$STACK_DIR/manager/public/app.js"
        if [ -f "$OVERRIDE" ]; then
            printf '\n  %slinked%s - the container is serving straight from the repo\n' "$GRN" "$R"
        else
            printf '\n  %snot linked%s - the container is serving the files baked into its image\n' "$YLW" "$R"
        fi
        # Compare what is actually being served against the working copy.
        # `wc -c` pads its output with spaces on BSD/macOS, so the string
        # comparison below fails on two identical numbers unless it is trimmed
        # the same way the served size already is.
        local_size=$(wc -c < "$REPO/manager/public/app.js" | tr -d ' \n')
        served_size=$($DOCKER_SUDO docker exec quickstart-home-manager sh -c 'wc -c < /app/public/app.js' 2>/dev/null | tr -d ' \n' || echo "?")
        printf '\n  repo app.js   %s bytes\n' "$local_size"
        printf '  served app.js %s bytes\n' "$served_size"
        if [ "$local_size" = "$served_size" ]; then
            printf '  %s-> in sync%s\n\n' "$GRN" "$R"
        else
            printf '  %s-> DIFFERENT: your edits are not live. Run ./dev.sh link%s\n\n' "$YLW" "$R"
        fi
        ;;

    *)
        die "Unknown command '${1}'. Use: link | watch | unlink | restart | sync | status"
        ;;
esac
